Repository puppetlabs/Puppet.Dsc, pull requests merged in 2020-12, with the labels that each got.

#95 (GH-94) Add debugging env to vagrant
  Vagrantfile
  extras/install.ps1
  extras/profile.ps1
Labels: maintenance

#97 (MAINT) Only write attributes if parameter is not null
  src/internal/functions/Get-TypeParameterContent.ps1
Labels: bug

#98 (MAINT) Ensure struct keys are downcased
  src/internal/functions/Get-DscResourceParameterInfoByCimClass.ps1
Labels: bug

#99 (GH-80) Typify read only properties
  src/internal/functions/Get-DscResourceParameterInfoByCimClass.ps1
  src/internal/functions/Get-TypeParameterContent.ps1
Labels: enhancement

#100 (GH-85) Make puppetizing prerelease modules switchable
  build.ps1
  src/functions/New-PuppetDscModule.ps1
  src/internal/functions/Add-DscResourceModule.ps1
  src/tests/functions/Add-DscResourceModule.Tests.ps1
Labels: bug

#91 (GH-59) Correct text in troubleshooting section
  src/internal/functions/Get-ReadmeContent.ps1
Labels: bug

#101 (MAINT) Update version pins for metadata.json
  src/internal/functions/Update-PuppetModuleMetadata.ps1
  src/tests/functions/Update-PuppetModuleMetadata.Tests.ps1
Labels: enhancement

#102 (MAINT) Sync changelog with prior changes
  CHANGELOG.md
Labels: maintenance

#103 (MAINT) Prep for 0.2.0 release
  CHANGELOG.md
  src/puppet.dsc.psd1
Labels: maintenance

#104 (Maint) Merge back for 0.2.0 release
  CHANGELOG.md
  src/puppet.dsc.psd1
Labels: maintenance

#106 (MAINT) Add Util Functions
  extras/install.ps1
  extras/util.ps1
  publish.ps1
  src/internal/functions/Get-PuppetModuleVersion.ps1
Labels: maintenance

#107 (MAINT) Add JoinOU to parameter list
  CHANGELOG.md
  src/internal/functions/Test-DscResourcePropertyParameterStatus.ps1
Labels: enhancement

#108 (MAINT) Ensure changelog actually updates
  CHANGELOG.md
  src/functions/New-PuppetDscModule.ps1
  src/tests/functions/New-PuppetDscModule.Tests.ps1
Labels: bug

#109 (MAINT) Prep for 0.3.0 release
  CHANGELOG.md
  src/puppet.dsc.psd1
Labels: maintenance

#110 (MAINT) Mergeback 0.3.0 Release
  CHANGELOG.md
  src/puppet.dsc.psd1
Labels: maintenance
