Repository puppetlabs/Puppet.Dsc, pull requests merged in 2020-04, with the labels that each got.

#2 (IAC-650) Scaffold Module Folders and Files
  Get-DscResourceTypeInformation.ps1
  build.ps1
  src/bin/readme.md
  src/en-us/about_puppet.dsc.help.txt
  src/en-us/strings.psd1
  src/functions/Get-DscResourceTypeInformation.ps1
  src/functions/readme.md
  src/internal/configurations/configuration.ps1
  src/internal/configurations/readme.md
  src/internal/functions/readme.md
  src/internal/scriptblocks/scriptblocks.ps1
  src/internal/scripts/license.ps1
  src/internal/scripts/postimport.ps1
  src/internal/scripts/preimport.ps1
  src/internal/scripts/strings.ps1
  src/internal/tepp/assignment.ps1
  src/internal/tepp/example.tepp.ps1
  src/internal/tepp/readme.md
  src/puppet.dsc.psd1
  src/puppet.dsc.psm1
  src/readme.md
  src/tests/functions/readme.md
  src/tests/general/FileIntegrity.Exceptions.ps1
  src/tests/general/FileIntegrity.Tests.ps1
  src/tests/general/Help.Exceptions.ps1
  src/tests/general/Help.Tests.ps1
  src/tests/general/Manifest.Tests.ps1
  src/tests/general/PSScriptAnalyzer.Tests.ps1
  src/tests/general/strings.Exceptions.ps1
  src/tests/general/strings.Tests.ps1
  src/tests/pester.ps1
  src/tests/readme.md
  src/xml/puppet.dsc.Format.ps1xml
  src/xml/puppet.dsc.Types.ps1xml
  src/xml/readme.md
Labels: enhancement

#4 Add Vagrantfile for reproducible tests and development environment
  .gitignore
  Vagrantfile
Labels: enhancement

#6 Enable appveyor
  Vagrantfile
  appveyor.yml
  extras/install.ps1
Labels: maintenance

#5 (IAC-668) Replace templating engine
  build.ps1
  extras/install.ps1
  src/functions/Get-ProviderContent.ps1
  src/functions/Get-TypeContent.ps1
  src/internal/functions/Get-TypeParameterContent.ps1
  src/internal/templates/static/.sync.yml
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/invoke_dsc_resource.ps1.erb
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_postscript.ps1.erb
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_preamble.ps1.erb
  src/internal/templates/static/lib/puppet_x/puppetlabs/dsc_api/dsc_template_helper.rb
  src/puppet.dsc.psd1
  src/tests/functions/Get-DscResourceParameterInfo.Tests.ps1
  src/tests/functions/Get-ProviderContent.Tests.ps1
  src/tests/functions/Get-TypeContent.Tests.ps1
  src/tests/functions/Get-TypeParameterContent.Tests.ps1
  src/xml/puppet.dsc.Types.ps1xml
Labels: maintenance

#9 (IAC-670) Fill out module manifest
  src/puppet.dsc.psd1
Labels: maintenance

#10 (IAC-699) Improve Puppet module metadata
  build.ps1
Labels: enhancement

#12 (MAINT) Add full build proc to CI
  appveyor.yml
  extras/install.ps1
Labels: maintenance

#13 (MAINT) Make Puppet runs quieter
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Labels: maintenance

#7 (IAC-664) Move module vendoring code to private Add-DscResourceModule…
  appveyor.yml
  build.ps1
  src/functions/Add-DscResourceModule.ps1
  src/puppet.dsc.psd1
  src/tests/functions/Add-DscResourceModule.Tests.ps1
Labels: maintenance

#16 (maint) Pin PowerShellGet module to ver 2.2.3
  extras/install.ps1
Labels: maintenance

#17 (IAC-710) Improve DSC Resource Type Handling
  src/internal/functions/Get-DscResourceParameterInfo.ps1
  src/internal/functions/Get-PuppetDataType.ps1
  src/internal/functions/Get-ShortType.ps1
  src/internal/functions/Get-TypeContent.ps1
  src/internal/functions/Test-EmbeddedInstance.ps1
  src/puppet.dsc.psd1
  src/tests/functions/Get-DscResourceParameterInfo.Tests.ps1
  src/tests/functions/Get-EmbeddedInstance.Tests.ps1
  src/tests/functions/Get-PuppetDataType.Tests.ps1
  src/tests/functions/Get-ShortType.Tests.ps1
Labels: enhancement

#19 Ensure Sensitive handling of PSCredentials; module version munging; DSC metadata in metadata.json
  src/functions/Update-PuppetModuleMetadata.ps1
  src/internal/functions/Get-PuppetDataType.ps1
  src/internal/functions/Get-PuppetModuleVersion.ps1
  src/tests/functions/Get-PuppetDataType.Tests.ps1
  src/tests/functions/Get-PuppetModuleVersion.Tests.ps1
  src/tests/functions/Update-PuppetModuleMetadata.Tests.ps1
Labels: bug, enhancement

#21 (IAC-708, IAC-709) Rework, document, and redact script generation in the base provider
  src/internal/functions/Get-PuppetDataType.ps1
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/invoke_dsc_resource.ps1.erb
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_postscript.ps1
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_postscript.ps1.erb
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_preamble.ps1
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_preamble.ps1.erb
  src/tests/functions/Get-PuppetDataType.Tests.ps1
Labels: enhancement
