Repository puppetlabs/Puppet.Dsc, pull requests merged in 2020-05, with the labels that each got.

#26 (IAC-740) Map embedded CIM instances if running elevated
  appveyor.yml
  build.ps1
  extras/install.ps1
  src/functions/New-PuppetDscModule.ps1
  src/internal/functions/Get-CimClassPropertiesList.ps1
  src/internal/functions/Get-DscResourceParameterInfo.ps1
  src/internal/functions/Get-DscResourceParameterInfoByCimClass.ps1
  src/internal/functions/Get-DscResourceTypeInformation.ps1
  src/internal/functions/Get-EmbeddedCimInstance.ps1
  src/internal/functions/Get-TypeParameterContent.ps1
  src/internal/functions/Initialize-DscResourceCimClass.ps1
  src/internal/functions/Test-RunningElevated.ps1
  src/internal/functions/Test-SymLinkedItem.ps1
  src/tests/functions/Get-CimClassPropertiesList.Tests.ps1
  src/tests/functions/Get-DscResourceParameterInfoByCimClass.Tests.ps1
  src/tests/functions/Get-DscResourceTypeInformation.Tests.ps1
  src/tests/functions/Get-EmbeddedCimInstance.Tests.ps1
  src/tests/functions/Initialize-DscResourceCimClass.Tests.ps1
  src/tests/functions/New-PuppetDscModule.Tests.ps1
  src/tests/functions/Test-SymLinkedItem.Tests.ps1
Labels: enhancement

#27 Ensure that metadata field `summary` is always less than 144 length
  src/internal/functions/Update-PuppetModuleMetadata.ps1
  src/tests/functions/Update-PuppetModuleMetadata.Tests.ps1
Labels: bug

#28 Enable parsing of composite resources
  src/internal/functions/Get-DscResourceParameterInfo.ps1
  src/internal/functions/Get-DscResourceTypeInformation.ps1
Labels: bug

#29 Add IAC team as CODEOWNER; Patch up Invoke-PdkCommand; typos
  CODEOWNERS
  src/functions/ConvertTo-PuppetResourceApi.ps1
  src/internal/functions/Invoke-PdkCommand.ps1
  src/tests/functions/Invoke-PdkCommand.Tests.ps1
Labels: maintenance

#24 (IAC-718) end to end tests for function-based DSC Resources
  appveyor.yml
  build.Tests.ps1
  src/functions/New-PuppetDscModule.ps1
  src/internal/functions/Add-PuppetReferenceDocumentation.ps1
  src/internal/functions/Get-DscResourceParameterInfoByCimClass.ps1
  src/internal/functions/Get-PuppetDataType.ps1
  src/internal/functions/Initialize-PuppetModule.ps1
  src/internal/functions/Invoke-PdkCommand.ps1
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  src/tests/functions/Add-PuppetReferenceDocumentation.Tests.ps1
  src/tests/functions/Get-PuppetDataType.Tests.ps1
  src/tests/functions/Invoke-PdkCommand.Tests.ps1
  src/tests/functions/New-PuppetDscModule.Tests.ps1
  src/tests/pester.ps1
Labels: bug, maintenance
