Repository puppetlabs/Puppet.Dsc, pull requests merged in 2020-11, with the labels that each got.

#76 (MAINT) Enable puppetizing prerelease modules
  src/internal/functions/Add-DscResourceModule.ps1
Labels: enhancement

#77 (GH-66) Ensure type desc strings parse for reference
  src/internal/functions/Get-TypeParameterContent.ps1
  src/tests/functions/Get-TypeParameterContent.Tests.ps1
Labels: bug

#78 (GH-71) Fix type def of props with optional nested cim instances
  src/internal/functions/Get-DscResourceParameterInfoByCimClass.ps1
Labels: bug

#82 (maint) Fix minor README.md typo
  README.md
Labels: maintenance

#83 (MAINT) Rework string interpolation for type files
  src/internal/functions/ConvertTo-PuppetRubyString.ps1
  src/internal/functions/Get-DscResourceParameterInfoByCimClass.ps1
  src/internal/functions/Get-PuppetDataType.ps1
  src/internal/functions/Get-TypeContent.ps1
  src/internal/functions/Get-TypeParameterContent.ps1
  src/tests/functions/ConvertTo-PuppetRubyString.Tests.ps1
  src/tests/functions/Get-DscResourceParameterInfo.Tests.ps1
  src/tests/functions/Get-DscResourceParameterInfoByCimClass.Tests.ps1
  src/tests/functions/Get-PuppetDataType.Tests.ps1
Labels: maintenance

#84 (GH-72) Clarify property usage in generated readme
  src/internal/functions/Get-ReadmeContent.ps1
Labels: enhancement

#88 (GH-74, GH-81) Handle parameters in type generation and collapse ensure keywords
  README.md
  build.Tests.ps1
  src/internal/functions/Get-DscResourceParameterInfo.ps1
  src/internal/functions/Get-DscResourceParameterInfoByCimClass.ps1
  src/internal/functions/Get-ReadmeContent.ps1
  src/internal/functions/Get-TypeContent.ps1
  src/internal/functions/Get-TypeParameterContent.ps1
  src/internal/functions/Test-DscResourcePropertyParameterStatus.ps1
  src/tests/functions/Get-DscResourceParameterInfo.Tests.ps1
  src/tests/functions/Get-DscResourceParameterInfoByCimClass.Tests.ps1
  src/tests/functions/Test-DscResourcePropertyParameterStatus.Tests.ps1
Labels: enhancement
