Repository puppetlabs/Puppet.Dsc, pull requests merged in 2020-09, with the labels that each got.

#49 (MAINT) Update pwshlib reference to 0.5.0
  src/internal/functions/Update-PuppetModuleMetadata.ps1
  src/tests/functions/Update-PuppetModuleMetadata.Tests.ps1
Labels: maintenance

#52 (MAINT) Minor fixes based on beta test feedback
  src/functions/New-PuppetDscModule.ps1
  src/puppet.dsc.psd1
Labels: maintenance

#53 (MAINT) Prep for initial release
  .gitignore
  README.md
  docs/about_Puppet.Dsc.md
  docs/about_Puppetization.md
  publish.ps1
  src/en-us/about_puppet.dsc.help.txt
  src/internal/functions/Get-ReadmeContent.ps1
  src/puppet.dsc.psd1
  src/tests/functions/Get-ReadmeContent.Tests.ps1
Labels: maintenance

#54 (maint) Correct links in README
  src/internal/functions/Get-ReadmeContent.ps1
Labels: bug

#55 (MAINT) Update version pin for pwshlib
  src/internal/functions/Update-PuppetModuleMetadata.ps1
  src/tests/functions/Update-PuppetModuleMetadata.Tests.ps1
Labels: maintenance

#57 (MAINT) Add function to update changelog
  src/internal/functions/Update-PuppetModuleChangelog.ps1
  src/tests/functions/Update-PuppetModuleChangelog.Tests.ps1
Labels: enhancement

#56 (MAINT) Add known limitations to generated readmes
  src/internal/functions/Get-ReadmeContent.ps1
Labels: enhancement

#58 (MAINT) Add project CHANGELOG file
  CHANGELOG.md
Labels: enhancement
