Repository puppetlabs/Puppet.Dsc, pull requests merged in 2020-07, with the labels that each got.

#36 (IAC-879) fix providername,Underscores are not valid.
  src/internal/functions/Get-ProviderContent.ps1
  src/tests/functions/Get-ProviderContent.Tests.ps1
Labels: bug

#38 (IAC-905) Map SInt datatyp to puppet data type
  src/internal/functions/Get-PuppetDataType.ps1
  src/internal/functions/Test-EmbeddedInstance.ps1
Labels: bug

#40 (IAC-720) Class based testcases
  build.Tests.ps1
Labels: maintenance

#39 (IAC-741) Implement Canonicalize for provider
  .gitignore
  build.Tests.ps1
  src/internal/functions/Get-DscResourceParameterInfo.ps1
  src/internal/functions/Get-DscResourceParameterInfoByCimClass.ps1
  src/internal/functions/Get-PuppetDataType.ps1
  src/internal/functions/Get-TypeContent.ps1
  src/internal/functions/Get-TypeParameterContent.ps1
  src/internal/functions/Invoke-PdkCommand.ps1
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_preamble.ps1
  src/tests/functions/Get-DscResourceParameterInfo.Tests.ps1
  src/tests/functions/Get-DscResourceParameterInfoByCimClass.Tests.ps1
  src/tests/functions/Get-PuppetDataType.Tests.ps1
  src/tests/functions/Get-TypeContent.Tests.ps1
  src/tests/functions/Get-TypeParameterContent.Tests.ps1
  src/tests/functions/Invoke-PdkCommand.Tests.ps1
Labels: enhancement

#41 (IAC-895) Implement query caching
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Labels: enhancement
