Repository puppetlabs/Puppet.Dsc, pull requests merged in 2020-08, with the labels that each got.

#42 (IAC-844) Allow using a local PSRepository
  src/functions/New-PuppetDscModule.ps1
  src/internal/functions/Add-DscResourceModule.ps1
  src/tests/functions/Add-DscResourceModule.Tests.ps1
  src/tests/functions/New-PuppetDscModule.Tests.ps1
Labels: enhancement

#43 (IAC-804) Implement PSDscRunAsCredential
  appveyor.yml
  build.Tests.ps1
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Labels: enhancement

#46 (maint) fix typo
  src/functions/Publish-PuppetModule.ps1
Labels: maintenance

#47 (IAC-716) Add troubleshooting documentation
  README.md
  src/functions/Publish-PuppetModule.ps1
  src/tests/functions/Publish-PuppetModule.Tests.ps1
  src/tests/pester.ps1
Labels: documentation
