Repository puppetlabs/Puppet.Dsc, pull requests merged in 2020-06, with the labels that each got.

#30 Fix YARD tag usage and implement Real32/Real64 data types
  src/internal/functions/Get-PuppetDataType.ps1
  src/internal/templates/static/lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Labels: enhancement

#31 (IAC-711) Add publish function
  src/functions/Publish-PuppetModule.ps1
  src/puppet.dsc.psd1
  src/tests/functions/Publish-PuppetModule.Tests.ps1
Labels: enhancement

#32 (IAC-861) Update CI scripts to fail AppVeyor runs on test failures
  appveyor.yml
  build.Tests.ps1
  extras/install.ps1
  src/tests/pester.ps1
Labels: maintenance

#33 (IAC-862) specify moduleauthorname to tests
  build.Tests.ps1
  extras/install.ps1
Labels: maintenance

#34 (IAC-846) Canonicalize Puppet module author names
  src/functions/New-PuppetDscModule.ps1
  src/internal/functions/ConvertTo-CanonicalPuppetAuthorName.ps1
  src/tests/functions/ConvertTo-CanonicalPuppetAuthorName.ps1
  src/tests/functions/New-PuppetDscModule.Tests.ps1
Labels: bug
