Repository puppetlabs/Puppet.Dsc, pull requests merged in 2021-06, with the labels that each got.

#160 (MAINT) Add debug info to install script
  appveyor.yml
  extras/install.ps1
Labels: maintenance

#161 (GH-64) Add docs for customizing private modules
  .gitignore
  docs/about_Puppetizing_Custom_Modules.md
Labels: documentation

#163 (GH-153) Ensure generated readme contains module name info
  CHANGELOG.md
  src/functions/New-PuppetDscModule.Tests.ps1
  src/functions/New-PuppetDscModule.ps1
  src/internal/functions/Get-ReadmeContent.Tests.ps1
  src/internal/functions/Get-ReadmeContent.ps1
  src/internal/functions/Update-PuppetModuleReadme.Tests.ps1
  src/internal/functions/Update-PuppetModuleReadme.ps1
Labels: enhancement

#162 (GH-149) Add long path info to generated readme
  CHANGELOG.md
  src/internal/functions/Get-ReadmeContent.ps1
Labels: documentation

#164 (GH-150) Add known installation limitations to readme
  CHANGELOG.md
  src/internal/functions/Get-ReadmeContent.ps1
Labels: documentation

#159 (GH-148) - Migrate Unit/General tests from Appveyor to GitHub Actions
  .github/workflows/spec.yml
  appveyor.yml
Labels: maintenance

#165 (GH-139) Clarification added regarding the DSC Local Configuration Manager (LCM)
  CHANGELOG.md
  src/internal/functions/Get-ReadmeContent.ps1
Labels: documentation

#170 (GH-148) Activate acceptance tests
  .github/workflows/spec.yml
Labels: enhancement

#172 (MAINT) Remove appveyor
  appveyor.yml
Labels: maintenance

#173 (MAINT) Move acceptance tests to folder and refactor acceptance testing CI Job
  .github/workflows/spec.yml
  acceptance/Basic.Tests.ps1
Labels: maintenance

#174 (MAINT) Tag and simplify test execution
  .github/workflows/spec.yml
  acceptance/Basic.Tests.ps1
  extras/invoke_tests.ps1
  src/functions/ConvertTo-PuppetResourceApi.Tests.ps1
  src/functions/Get-PuppetizedModuleName.Tests.ps1
  src/functions/New-PuppetDscModule.Tests.ps1
  src/functions/Publish-PuppetModule.Tests.ps1
  src/internal/functions/Add-DscResourceModule.Tests.ps1
  src/internal/functions/Add-PuppetReferenceDocumentation.Tests.ps1
  src/internal/functions/ConvertTo-CanonicalPuppetAuthorName.Tests.ps1
  src/internal/functions/ConvertTo-PuppetRubyString.Tests.ps1
  src/internal/functions/ConvertTo-UnescapedJson.Tests.ps1
  src/internal/functions/Get-CimClassPropertiesList.Tests.ps1
  src/internal/functions/Get-DscResourceParameterInfo.Tests.ps1
  src/internal/functions/Get-DscResourceParameterInfoByCimClass.Tests.ps1
  src/internal/functions/Get-DscResourceTypeInformation.Tests.ps1
  src/internal/functions/Get-EmbeddedCimInstance.Tests.ps1
  src/internal/functions/Get-ProviderContent.Tests.ps1
  src/internal/functions/Get-PuppetDataType.Tests.ps1
  src/internal/functions/Get-PuppetModuleVersion.Tests.ps1
  src/internal/functions/Get-ReadmeContent.Tests.ps1
  src/internal/functions/Get-ShortType.Tests.ps1
  src/internal/functions/Get-TypeContent.Tests.ps1
  src/internal/functions/Get-TypeParameterContent.Tests.ps1
  src/internal/functions/Initialize-DscResourceCimClass.Tests.ps1
  src/internal/functions/Initialize-PuppetModule.Tests.ps1
  src/internal/functions/Invoke-PdkCommand.Tests.ps1
  src/internal/functions/Out-Utf8File.Tests.ps1
  src/internal/functions/Set-PSModulePath.Tests.ps1
  src/internal/functions/Test-DscResourcePropertyParameterStatus.Tests.ps1
  src/internal/functions/Test-EmbeddedInstance.Tests.ps1
  src/internal/functions/Test-RunningElevated.Tests.ps1
  src/internal/functions/Test-SymLinkedItem.Tests.ps1
  src/internal/functions/Update-PuppetModuleChangelog.Tests.ps1
  src/internal/functions/Update-PuppetModuleFixture.Tests.ps1
  src/internal/functions/Update-PuppetModuleMetadata.Tests.ps1
  src/internal/functions/Update-PuppetModuleReadme.Tests.ps1
  src/tests/general/FileIntegrity.Tests.ps1
  src/tests/general/Help.Tests.ps1
  src/tests/general/Manifest.Tests.ps1
  src/tests/general/PSScriptAnalyzer.Tests.ps1
Labels: maintenance

#175 (MAINT) Update install script and vagrantfile
  Vagrantfile
  extras/install.ps1
Labels: maintenance

#166 (GH-62) Add acceptance testing for multi-module scenario
  .github/workflows/spec.yml
  acceptance/MultiModule.Tests.ps1
  examples/webserver/webserver_template.pp
  examples/webserver/website/index.html
  extras/install.ps1
  extras/invoke_tests.ps1
Labels: maintenance

#147 (GH-145) Add validation mode flag to puppetized DSC Resources
  CHANGELOG.md
  acceptance/Basic.Tests.ps1
  src/internal/functions/Get-ReadmeContent.ps1
  src/internal/functions/Get-TypeContent.Tests.ps1
  src/internal/functions/Get-TypeContent.ps1
  src/internal/functions/Update-PuppetModuleMetadata.Tests.ps1
  src/internal/functions/Update-PuppetModuleMetadata.ps1
Labels: enhancement

#177 Mergeback 0.6.0 Release
  CHANGELOG.md
  src/puppet.dsc.psd1
Labels: maintenance
