Repository puppetlabs/Puppet.Dsc, pull requests merged in 2021-02, with the labels that each got.

#122 (GH-114) - Adding PSCredential and CIM Instance examples
  src/internal/functions/Get-ReadmeContent.ps1
Labels: documentation

#124 (MAINT) Add CertReq parameters to hard-coded list
  CHANGELOG.md
  src/internal/functions/Test-DscResourcePropertyParameterStatus.ps1
Labels: enhancement

#127 (GH-113) Vendor modules not found in module repo
  CHANGELOG.md
  src/internal/functions/Add-DscResourceModule.ps1
  src/tests/functions/Add-DscResourceModule.Tests.ps1
Labels: enhancement

#128 (Maint) Prep for 0.5.0 Release
  CHANGELOG.md
  src/puppet.dsc.psd1
Labels: maintenance

#129 (Maint) Mergeback 0.5.0 Release
  CHANGELOG.md
  src/puppet.dsc.psd1
Labels: maintenance
