Repository puppetlabs/Puppet.Dsc, pull requests merged in 2023-11, with the labels that each got.

#268 (MAINT) - temp pin pdk 2.7.1
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/puppetize.yml
  .github/workflows/repuppetize.yml
Labels: maintenance

#269 (CAT-1484) - Add ensurable property to resource
  .gitignore
  docs/architecture/decisions/0001-force-ensurable.md
  src/Puppet.Dsc/internal/functions/Get-TypeContent.ps1
  src/Puppet.Dsc/internal/functions/Get-TypeParameterContent.ps1
Labels: bugfix

#270 (maint) - Add an illustration to the design document.
  docs/architecture/decisions/0001-force-ensurable.md
Labels: maintenance

#273 (CAT-1454) - Add Puppet 8/Drop Puppet 6
  src/Puppet.Dsc/internal/functions/Update-PuppetModuleMetadata.Tests.ps1
  src/Puppet.Dsc/internal/functions/Update-PuppetModuleMetadata.ps1
Labels: backwards-incompatible

#276 (maint) - Remove Puppet.Dsc from module cache
  .github/workflows/puppetize.yml
  .github/workflows/repuppetize.yml
Labels: maintenance
